CREATE TABLE tblUsers(
	UserID VARCHAR(36) PRIMARY KEY,
	FirstName VARCHAR(100) NOT NULL,
	Username VARCHAR(100) NOT NULL,
	Password VARCHAR(900) NOT NULL,
	Troop VARCHAR(10) NOT NULL,
	Email VARCHAR(400) NOT NULL
);

CREATE TABLE tblUserPointValues(
	PointID VARCHAR(36) PRIMARY KEY,
	UserID VARCHAR(36) NOT NULL,
	PointValue INTEGER NOT NULL
);

CREATE TABLE tblUserPointTotals(
	RecordID VARCHAR(36) PRIMARY KEY,
	UserID VARCHAR(36) NOT NULL,
	PointTotal INTEGER NOT NULL
);

CREATE TABLE tblPointsRewardedRecord(
	RecordID VARCHAR(36) NOT NULL,
	ScanUserID VARCHAR(36) NOT NULL,
	ScanneeUserID VARCHAR(36) NOT NULL,
	PointsRewarded INTEGER NOT NULL,
	RecordDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	
);